export { startSession } from './startSession'
export { assignVariation } from './assignVariation'
export { clearVariation } from './clearVariation'
export { addSet } from './addSet'
export { removeLastSet } from './removeLastSet'
export { completeSession } from './completeSession'
export { abandonSession } from './abandonSession'
export { getLastVariationsForMuscleGroup } from './getLastVariationsForMuscleGroup'

export type { TrainingSession, SessionEntry, SessionSet, SessionStatus } from '@domain/sessions/TrainingSession'
export type { Weight } from '@domain/shared/Weight'
export { parseWeight } from '@domain/shared/Weight'
